/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuardianViewRouteImport } from './routes/guardian.view'
import { Route as ConciergeDeskRouteImport } from './routes/concierge.desk'
import { Route as ArtisanTodayRouteImport } from './routes/artisan.today'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianViewRoute = GuardianViewRouteImport.update({
  id: '/guardian/view',
  path: '/guardian/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeDeskRoute = ConciergeDeskRouteImport.update({
  id: '/concierge/desk',
  path: '/concierge/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanTodayRoute = ArtisanTodayRouteImport.update({
  id: '/artisan/today',
  path: '/artisan/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artisan/today': typeof ArtisanTodayRoute
  '/concierge/desk': typeof ConciergeDeskRoute
  '/guardian/view': typeof GuardianViewRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artisan/today': typeof ArtisanTodayRoute
  '/concierge/desk': typeof ConciergeDeskRoute
  '/guardian/view': typeof GuardianViewRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artisan/today': typeof ArtisanTodayRoute
  '/concierge/desk': typeof ConciergeDeskRoute
  '/guardian/view': typeof GuardianViewRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artisan/today'
    | '/concierge/desk'
    | '/guardian/view'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artisan/today'
    | '/concierge/desk'
    | '/guardian/view'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/artisan/today'
    | '/concierge/desk'
    | '/guardian/view'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtisanTodayRoute: typeof ArtisanTodayRoute
  ConciergeDeskRoute: typeof ConciergeDeskRoute
  GuardianViewRoute: typeof GuardianViewRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/view': {
      id: '/guardian/view'
      path: '/guardian/view'
      fullPath: '/guardian/view'
      preLoaderRoute: typeof GuardianViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge/desk': {
      id: '/concierge/desk'
      path: '/concierge/desk'
      fullPath: '/concierge/desk'
      preLoaderRoute: typeof ConciergeDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/today': {
      id: '/artisan/today'
      path: '/artisan/today'
      fullPath: '/artisan/today'
      preLoaderRoute: typeof ArtisanTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtisanTodayRoute: ArtisanTodayRoute,
  ConciergeDeskRoute: ConciergeDeskRoute,
  GuardianViewRoute: GuardianViewRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
