/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as SurprisesRouteImport } from './routes/surprises'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PerksRouteImport } from './routes/perks'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BrunchRouteImport } from './routes/brunch'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptsIdRouteImport } from './routes/receipts.$id'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa.callback'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const SurprisesRoute = SurprisesRouteImport.update({
  id: '/surprises',
  path: '/surprises',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PerksRoute = PerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BrunchRoute = BrunchRouteImport.update({
  id: '/brunch',
  path: '/brunch',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIdRoute = ReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/brunch': typeof BrunchRoute
  '/clients': typeof ClientsRoute
  '/founders': typeof FoundersRoute
  '/payments': typeof PaymentsRoute
  '/perks': typeof PerksRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/surprises': typeof SurprisesRoute
  '/whatsapp': typeof WhatsappRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/brunch': typeof BrunchRoute
  '/clients': typeof ClientsRoute
  '/founders': typeof FoundersRoute
  '/payments': typeof PaymentsRoute
  '/perks': typeof PerksRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/surprises': typeof SurprisesRoute
  '/whatsapp': typeof WhatsappRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/brunch': typeof BrunchRoute
  '/clients': typeof ClientsRoute
  '/founders': typeof FoundersRoute
  '/payments': typeof PaymentsRoute
  '/perks': typeof PerksRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/surprises': typeof SurprisesRoute
  '/whatsapp': typeof WhatsappRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/brunch'
    | '/clients'
    | '/founders'
    | '/payments'
    | '/perks'
    | '/products'
    | '/settings'
    | '/surprises'
    | '/whatsapp'
    | '/receipts/$id'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/brunch'
    | '/clients'
    | '/founders'
    | '/payments'
    | '/perks'
    | '/products'
    | '/settings'
    | '/surprises'
    | '/whatsapp'
    | '/receipts/$id'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/brunch'
    | '/clients'
    | '/founders'
    | '/payments'
    | '/perks'
    | '/products'
    | '/settings'
    | '/surprises'
    | '/whatsapp'
    | '/receipts/$id'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BrunchRoute: typeof BrunchRoute
  ClientsRoute: typeof ClientsRoute
  FoundersRoute: typeof FoundersRoute
  PaymentsRoute: typeof PaymentsRoute
  PerksRoute: typeof PerksRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  SurprisesRoute: typeof SurprisesRoute
  WhatsappRoute: typeof WhatsappRoute
  ReceiptsIdRoute: typeof ReceiptsIdRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surprises': {
      id: '/surprises'
      path: '/surprises'
      fullPath: '/surprises'
      preLoaderRoute: typeof SurprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perks': {
      id: '/perks'
      path: '/perks'
      fullPath: '/perks'
      preLoaderRoute: typeof PerksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brunch': {
      id: '/brunch'
      path: '/brunch'
      fullPath: '/brunch'
      preLoaderRoute: typeof BrunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$id': {
      id: '/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof ReceiptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  BrunchRoute: BrunchRoute,
  ClientsRoute: ClientsRoute,
  FoundersRoute: FoundersRoute,
  PaymentsRoute: PaymentsRoute,
  PerksRoute: PerksRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  SurprisesRoute: SurprisesRoute,
  WhatsappRoute: WhatsappRoute,
  ReceiptsIdRoute: ReceiptsIdRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
