/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangePinRouteImport } from './routes/change-pin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuardianViewRouteImport } from './routes/guardian.view'
import { Route as ConciergeDeskRouteImport } from './routes/concierge.desk'
import { Route as BillingCheckoutRouteImport } from './routes/billing.checkout'
import { Route as ArtisanTodayRouteImport } from './routes/artisan.today'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa.callback'
import { Route as ApiPublicHooksVisitReminders21dRouteImport } from './routes/api/public/hooks/visit-reminders-21d'

const ChangePinRoute = ChangePinRouteImport.update({
  id: '/change-pin',
  path: '/change-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianViewRoute = GuardianViewRouteImport.update({
  id: '/guardian/view',
  path: '/guardian/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeDeskRoute = ConciergeDeskRouteImport.update({
  id: '/concierge/desk',
  path: '/concierge/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCheckoutRoute = BillingCheckoutRouteImport.update({
  id: '/billing/checkout',
  path: '/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanTodayRoute = ArtisanTodayRouteImport.update({
  id: '/artisan/today',
  path: '/artisan/today',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksVisitReminders21dRoute =
  ApiPublicHooksVisitReminders21dRouteImport.update({
    id: '/api/public/hooks/visit-reminders-21d',
    path: '/api/public/hooks/visit-reminders-21d',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-pin': typeof ChangePinRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/artisan/today': typeof ArtisanTodayRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/concierge/desk': typeof ConciergeDeskRoute
  '/guardian/view': typeof GuardianViewRoute
  '/api/public/hooks/visit-reminders-21d': typeof ApiPublicHooksVisitReminders21dRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-pin': typeof ChangePinRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/artisan/today': typeof ArtisanTodayRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/concierge/desk': typeof ConciergeDeskRoute
  '/guardian/view': typeof GuardianViewRoute
  '/api/public/hooks/visit-reminders-21d': typeof ApiPublicHooksVisitReminders21dRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-pin': typeof ChangePinRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/artisan/today': typeof ArtisanTodayRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/concierge/desk': typeof ConciergeDeskRoute
  '/guardian/view': typeof GuardianViewRoute
  '/api/public/hooks/visit-reminders-21d': typeof ApiPublicHooksVisitReminders21dRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-pin'
    | '/admin/partners'
    | '/artisan/today'
    | '/billing/checkout'
    | '/concierge/desk'
    | '/guardian/view'
    | '/api/public/hooks/visit-reminders-21d'
    | '/api/public/mpesa/callback'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-pin'
    | '/admin/partners'
    | '/artisan/today'
    | '/billing/checkout'
    | '/concierge/desk'
    | '/guardian/view'
    | '/api/public/hooks/visit-reminders-21d'
    | '/api/public/mpesa/callback'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/change-pin'
    | '/admin/partners'
    | '/artisan/today'
    | '/billing/checkout'
    | '/concierge/desk'
    | '/guardian/view'
    | '/api/public/hooks/visit-reminders-21d'
    | '/api/public/mpesa/callback'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePinRoute: typeof ChangePinRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  ArtisanTodayRoute: typeof ArtisanTodayRoute
  BillingCheckoutRoute: typeof BillingCheckoutRoute
  ConciergeDeskRoute: typeof ConciergeDeskRoute
  GuardianViewRoute: typeof GuardianViewRoute
  ApiPublicHooksVisitReminders21dRoute: typeof ApiPublicHooksVisitReminders21dRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/change-pin': {
      id: '/change-pin'
      path: '/change-pin'
      fullPath: '/change-pin'
      preLoaderRoute: typeof ChangePinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/view': {
      id: '/guardian/view'
      path: '/guardian/view'
      fullPath: '/guardian/view'
      preLoaderRoute: typeof GuardianViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge/desk': {
      id: '/concierge/desk'
      path: '/concierge/desk'
      fullPath: '/concierge/desk'
      preLoaderRoute: typeof ConciergeDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/checkout': {
      id: '/billing/checkout'
      path: '/billing/checkout'
      fullPath: '/billing/checkout'
      preLoaderRoute: typeof BillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/today': {
      id: '/artisan/today'
      path: '/artisan/today'
      fullPath: '/artisan/today'
      preLoaderRoute: typeof ArtisanTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/visit-reminders-21d': {
      id: '/api/public/hooks/visit-reminders-21d'
      path: '/api/public/hooks/visit-reminders-21d'
      fullPath: '/api/public/hooks/visit-reminders-21d'
      preLoaderRoute: typeof ApiPublicHooksVisitReminders21dRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePinRoute: ChangePinRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  ArtisanTodayRoute: ArtisanTodayRoute,
  BillingCheckoutRoute: BillingCheckoutRoute,
  ConciergeDeskRoute: ConciergeDeskRoute,
  GuardianViewRoute: GuardianViewRoute,
  ApiPublicHooksVisitReminders21dRoute: ApiPublicHooksVisitReminders21dRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
